# -*- coding: utf-8 -*-
"""OCRusingTesseract.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19ekYcMQ_To3hISrp_fX76fOvdmkzfNdT
"""

#!pip install pytesseract pdf2image --no-deps

fname = "IMG_20210804_0004.1.pdf" # File PDF cần chạy OCR

# import module
from pdf2image import convert_from_path

# Store Pdf with convert_from_path function
images = convert_from_path(fname)
 
for i in range(1, len(images)):
   
      # Save pages as images in the pdf
    images[i].save('page'+ str(i) +'.jpg', 'JPEG')