# -*- coding: utf-8 -*-
"""OCRusingTesseract.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19ekYcMQ_To3hISrp_fX76fOvdmkzfNdT
"""
# import module
from pdf2image import convert_from_path
import os

#!pip install pytesseract pdf2image --no-deps

path = "./raw_pdf"
fname = "./raw_pdf/" # File PDF cần chạy OCR

list = os.listdir(os.path.expanduser(path)) # Danh sách các file pdf

# Store Pdf with convert_from_path function


page = 0

for i in range(0, len(list)):
  print (str(fname + list[i]))
  images = convert_from_path(str(fname + list[i]))
  print(len(images))
  for j in range(0, len(images)):
    # Save pages as images in the pdf
    images[j].save('./source_input_from_pdf/page'+ str(page) +'.jpg', 'JPEG')
    page = page + 1
    print(page)
  